FirstSite/FirstSite/Models/Car.cs
namespace FirstSite.Models
{
	public class Car
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string Type {  get; set; }
		public decimal Price { get; set; }
		public string? Discription { get; set; }

	}
}

FirstSite/FirstSite/Models/MyDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace FirstSite.Models
{
	public class MyDbContext: DbContext
	{
		public MyDbContext(DbContextOptions<MyDbContext> options): base(options)
		{ }

		public DbSet<Car> Cars { get; set; }
	}
}

FirstSite/FirstSite/Controllers/MainController.cs
using FirstSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Controllers
{
    public class MainController : Controller
    {
        private readonly ILogger<MainController> _logger;

        private readonly MyDbContext myDbContext;
        
        public MainController(ILogger<MainController> logger, MyDbContext context) 
        {
            _logger = logger;
            myDbContext = context;
        }

        public IActionResult MainPage()
        {
            var cars = myDbContext.Cars.ToList();
            return View(cars);
        }

        [HttpPost]
        public async  Task<IActionResult> Delete(int id) 
        {
            var car = await myDbContext.Cars.FirstOrDefaultAsync(x => x.Id == id);
            myDbContext.Cars.Remove(car);
			await myDbContext.SaveChangesAsync();
            return RedirectToAction("MainPage");
        }

        [HttpPost]
        public async Task<IActionResult> Add(string name, string type, string price, string discription)
        {
            try 
            {
				var car = new Car() { Name = name, Type = type, Price = Convert.ToDecimal(price), Discription = discription };
				myDbContext.Cars.Add(car);
				await myDbContext.SaveChangesAsync();
			}
            catch 
            {
				
			}
			return RedirectToAction("MainPage");
		}

		[HttpPost]
		public async Task<IActionResult> Edit(string name, string type, string price, string discription, int id)
		{
            try 
            {
				var car = await myDbContext.Cars.FirstOrDefaultAsync(x => x.Id == id);
				car.Name = name;
				car.Type = type;
				car.Price = Convert.ToDecimal(price);
				car.Discription = discription;

				myDbContext.Cars.Update(car);
				await myDbContext.SaveChangesAsync();
			}
            catch 
            {
                
            }
            
			return RedirectToAction("MainPage");
		}
	}
}

FirstSite/FirstSite/Controllers/WebAPIController.cs
using FirstSite.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Controllers;

namespace FirstSite.Controllers
{
	
    [ApiController]
	[Route("api/WebAPIController")]
	public class WebAPIController : ControllerBase
    {
		private readonly MyDbContext myDbContext;

		public WebAPIController(MyDbContext _myDbContext) { 
            myDbContext = _myDbContext;
        }
		
        [HttpGet]

		public List<Car> GetCars()
        {
			var cars = myDbContext.Cars.ToList();
			return cars;
        }

		[HttpDelete("{id}")]
		public async void Delete( int id)
        {
			var car = myDbContext.Cars.FirstOrDefault(x=> x.Id == id);
			myDbContext.Cars.Remove(car);
			myDbContext.SaveChanges();
			
		}

		[HttpPost]
		public async void Add(Car car) 
		{
			try 
			{
				myDbContext.Cars.Add(car);
				myDbContext.SaveChanges();
			}
			catch { }
			
		}

		[HttpPut]
		public async void Edit([FromForm]Car car) 
		{

			try
			{
				myDbContext.Cars.Update(car);
				myDbContext.SaveChanges();
			}
			catch { }
		}
        
    }
}

FirstSite/FirstSite/Views/Main/MainPage.cshtml
@{
	ViewData["Title"] = "Home Page";
}

@model IEnumerable<FirstSite.Models.Car>

<html>
<head>
    <meta charset="utf-8" />
    <title>Main Page</title>
	<link href="/css/site.css" rel="stylesheet" />
</head>
<body>
    <div style="height: 7%">
		<p align="center"  style="color:#EDB749; font-size:50px; font-family:'Times New Roman', Times, serif;">Машины</p>
    </div>
    <div align="center" style="height: 80%" class="div_table">
		<table class="table_dark">
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Type</th>
				<th>Price</th>
				<th>Discripton</th>
			</tr>
		</thead>
		<tbody>
			@foreach(var car in Model)
			{
				<tr>
					<form asp-controller="Main" asp-action="Edit" asp-route-id="@car.Id">
					<td>@car.Id</td>
						<td><input type="text" name="name" value="@car.Name" /></td>
						<td><input type="text" name="type" value="@car.Type" /></td>
						<td><input type="text" name="price" value="@car.Price" />$</td>
						<td><input type="text" name="discription" value="@car.Discription" /></td>
						<td>
							<button type="submit" style="width:100%;">Сохранить</button>
						</td>
						
						</form>
					<td>

						<form asp-controller="Main" asp-action="Delete" asp-route-id="@car.Id">
							<button  type="submit" style="width:100%;">Удалить</button>

						</form>	
					</td>
						
				</tr>
			}
			
		</tbody>
		</table>

    </div>
	<div style="height:3%">
		<p align="center" style="color:#EDB749; font-size:25px; font-family:'Times New Roman', Times, serif;"> Добавление </p>
	</div>
	<div style="width:100%;height:3%; display:table">


		
					<form asp-controller="Main" asp-action="Add">
			<div  style="width:280px ; display:table-cell">
				<input type="text" name="name" value="Name" />
				</div>
			<div style="width:280px ; display:table-cell">
				<input type="text" name="type" value="Type" />	
					</div>
			<div style="width:280px ; display:table-cell">
				<input type="text" name="price" value="Price" />
					</div>

			<div style="width:280px ; display:table-cell">
				<input type="text" name="discription" value="Discription" />
					</div>


			<div style="width:23% ; display:table-cell">
				<button type="submit" style="width:100%">Добавить</button>
						</div>
				

						
					
					</form>
			
	</div>
</body>
</html>